export const DESCRIPTION =
  "Personal website of Antônio Pataro, a Software Engineer from Brazil specializing in full-stack development. Features professional experience, education background, and achievements, showcasing expertise in Node.js, Go, and modern web technologies. Includes a portfolio of work experiences at travel-tech, fintech, data protection and educational companies, along with academic achievements including a Bronze Medal in the Brazilian Mathematics Olympiad.";

export const EMAIL = "antoniopataro@gmail.com";

export const FIRST_YEAR_OF_EXPERIENCE = 2021;

export const HEADER_LINKS = [
  {
    href: "/",
    label: "Home",
  },
  {
    href: "/experience",
    label: "Experience",
  },
];

export const KEYWORDS = [
  "Antônio Pataro",
  "Software Engineer",
  "Fullstack Engineer",
  "Node.js",
  "Go",
  "React",
  "Next.js",
  "Golang",
  "TypeScript",
  "Web Development",
  "Travel-tech",
  "Fintech",
  "Data Protection",
  "Educational Technology",
  "AWS",
  "Clean Architecture",
  "Test-Driven Development",
  "TDD",
  "REST APIs",
  "GraphQL",
  "Microservices",
  "Front-end Development",
  "Back-end Development",
  "Aerospace Engineering",
  "Computer Science",
  "Brazilian Mathematics Olympiad",
  "OBMEP",
  "UFMG",
  "Professional Portfolio",
  "Technical Leadership",
  "System Architecture",
  "Cloud Infrastructure",
  "Brazil",
  "Angular",
  "Bitbucket",
  "CI/CD",
  "Docker",
  "Express.js",
  "Figma",
  "Git",
  "Github Actions",
  "gRPC",
  "Jest",
  "MatLab",
  "MongoDB",
  "MySQL",
  "NestJS",
  "OpenSearch",
  "PostgreSQL",
  "Prisma",
  "PWA",
  "Python",
  "R",
  "RabbitMQ",
  "React.js",
  "Rancher",
  "ReactEmail",
  "Redis",
  "Redux",
  "Redux Saga",
  "Resend",
  "Sass",
  "SciDAVis",
  "Sentry",
  "Sequelize",
  "SOLID",
  "Storybook",
  "TypeORM",
  "Vite",
  "Vitest",
  "Vue.js",
];
